Fix: error github workspace,
mazipan/auto-commit pull request #7
Opened 2022-04-29 09:35 UTC by mandaputtra

Fix these error on CI, keep the forest green

```
Push to branch ***************
fatal: unsafe repository ('/github/workspace' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace
```

2022-05-04 17:16 UTC, madfauzy requested changes
For line 50 Change `force: true` to `force-with-lease: true`. This will fix below error.

```
Run ad-m/github-push-action@master
  with:
    force: true
    directory: .
    github_token: ***
    github_url: https://github.com
Push to branch master
To https://github.com/madfauzy/Auto-Commit.git
 ! [rejected]        HEAD -> master (stale info)
error: failed to push some refs to 'https://github.com/madfauzy/Auto-Commit.git'
Error: Invalid exit code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:[2](https://github.com/madfauzy/Auto-Commit/runs/6294304367?check_suite_focus=true#step:5:2)9:21)
    at ChildProcess.emit (events.js:[3](https://github.com/madfauzy/Auto-Commit/runs/6294304367?check_suite_focus=true#step:5:3)1[4](https://github.com/madfauzy/Auto-Commit/runs/6294304367?check_suite_focus=true#step:5:4):20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:[5](https://github.com/madfauzy/Auto-Commit/runs/6294304367?check_suite_focus=true#step:5:5)) {
  code: 1
}
Error: Invalid exit code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:29:21)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:1[6](https://github.com/madfauzy/Auto-Commit/runs/6294304367?check_suite_focus=true#step:5:6))
    at Process.ChildProcess._handle.onexit (internal/child_process.js:28[7](https://github.com/madfauzy/Auto-Commit/runs/6294304367?check_suite_focus=true#step:5:7):5)
```

2022-05-04 17:17 UTC, madfauzy commented on .github/workflows/autocommit.yml
>            force: true
For line 50 Change `force: true` to `force-with-lease: true`

2022-05-04 17:31 UTC, madfauzy commented on .github/workflows/autocommit.yml
>            force: true
Change `force: true` To `force-with-lease`

2022-05-23 22:28 UTC, mazipan approved these changes
LGTM ✅

2022-05-23 22:28 UTC, merged